require('basic')
require('plugins')
require('mappings')

-- require('plugins._coc')
require('plugins._nvimtree')
require('plugins._tagbar')
require('plugins._commentary')
require('plugins._fzf')
require('plugins._omnisharp')
require('plugins._ale')
require('plugins._dart')
